### ISSUE TITLE
Missing feature collection/General Todo Collection

### ISSUE THREAD

**Issue by steffengy** [steffengy/tiberius#2]
Just sharing the last state of my todo list here,
in case somebody wants to play around with something:

- [ ] documentation
- [ ] ci
- [ ] support for TDS 7.3B >= tds 7.2 
(for now it's 7.3A, generally prepare support for multiple versions) 
**this requires passing the version & general information INTO the decode/encode funcs **             
       (will require refactoring)
- [ ] several more data type impls (prepare & unpack)
- [ ] sspi/ntlm auth (windows)

**Comment by SonicZentropy** [comment]
Not sure if you're still working on these or not, but the missing type impls (Specifically BigChar) are forcing me to use the raw odbc crate instead.  If you can drop me a hint or two as to what all needs to be done to get the support working, I can surely try it myself

**Comment by steffengy** [comment]
Generally:
- read the MS-TDS spec and check how your type is encoded
- search for the most similar type thats already supported (e.g. `NChar`)
- implement it, add a test 

All in https://github.com/steffengy/tiberius/blob/master/tiberius/src/types/mod.rs

**Comment by klmallory** [comment]
I don't see any reference to Table valued parameters. Is this on the todo list at some point? It is supported in TDS 7.3 and above:

https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-how-to/use-table-valued-parameters-odbc?view=sql-server-ver15

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/c264db71-c1ec-4fe8-b5ef-19d54b1e6566

Great job, by the way. Making leaps and bounds with micro-service architecture Rust because of this library.

**Comment by steffengy** [comment]
@klmallory 
You're the first asking so far :)
Feel free to open an extra issue for it mentioning some usecases/why its important for you.
Personally I'm currently busy with slowly making progress with porting to async/await,
so maybe next year sometime.
